### ISSUE TITLE
FHD - WQHD Screen replacement - HiDPI

### ISSUE THREAD

**Issue by kskim7** [kushwavez/lenovo-x1c6-clover-efi#3]
Hey Kushwavez my bro,

I've just upgraded my screen to the WQHD one.

Working just fine without any kext changes to the EFI.

However, when changed to the new screen, the resolution becomes 2K on 14 inch screen, making everything look so small.

So what I had to do is enable the HiDpi feature via

https://github.com/xzhih/one-key-hidpi

And it works just fine.

Now I have to check how fast the new screen drains the battery. 

I wish it would last at least 3 hours.

Here's the screenshot.

[IMG_4712](https://user-images.githubusercontent.com/78552041/112080446-5e30b280-8bc5-11eb-833c-a66dcabdf160.jpg)

* During the installation, I have broken some plastics which holds the cables underneath the screen . Be careful with that. 
* Putting cables into the screen hinge can be quite tricky. Pay extra attention to that part.

**Comment by kushwavez** [comment]
Thanks for the report! 
Glad it's working for you. Looks good!
