### ISSUE TITLE
CPU low utilization but high power consumption?

### ISSUE THREAD

**Issue by vzku2** [kushwavez/lenovo-x1c6-clover-efi#4]
Hi,

Your post is great and everything works well on my x1c6 except one minor part. The cpu is heating up to 75C with 20 watts power consumption even at idle (10% cpu utilization).

One of the noticeable difference of my machine is it has a i7-8550U. I am pretty much new on this, but could you provide some hints on how to resolve this? I tried one-key-cpufriend, however, it doesn't help. My research so far pointed that could be something related to SSDT, but I don't know exactly which SSDT to change.

Thanks again for this great project!

![Screen Shot 2021-09-06 at 9 03 40 PM](https://user-images.githubusercontent.com/30291669/132269398-c644e361-9fd8-4bd5-b0bc-cc758b1a7e48.png)

P.S. the cpu works normally and cool in windows

**Comment by kushwavez** [comment]
10% CPU util and this high Power usage sounds like something is running in the bg. 

To narrow down the issue please ensure that you have nothing running in the background (for ex. Audio EQs, System wide programs like adblockers) then check the utilization with Activity, or with terminal top command. 

If it’s still hot and the utilization is big, then please disable the TB3 in BIOS and let’s see if it’s still the case.

**Comment by vzku2** [comment]
Thank you for the suggestion. It seems the issue did come from the TB3.

There wasn't an option to disable TB3 in bios, instead I changed _Thunderbolt BIOS Assist Mode_ from Enabled to Disabled and everything cools down (2w cpu power in idle and 50C in temperature). one-key-cpufriend also helped to lower the min freq in this case.

<img width="406" alt="Screen Shot 2021-09-07 at 9 51 30 AM" src="https://user-images.githubusercontent.com/30291669/132357112-b06496e7-ddbd-43e3-b24a-27fe3336ff81.png">

**Comment by kushwavez** [comment]
I see. thanks for testing. 
So basically the thing is that there is a problem with TB3 power states. 

PC and Apple mechanic with power-controlling the TB3 is different, and in this case the TB3 controller is always on state so it’s consuming power. 
It is the case for me too, but for me it’s around 2-3W not 20W. 

Unfortunately it is quite difficult to replicate the Apple way, I can’t really do anything about it.
